apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
#  namespace: phpmyadmin
spec:
  type: NodePort
  ports:
    - nodePort: 31317
      port: 8081
      protocol: TCP
      targetPort: 8081
#    port: 8081
  selector:
    app: phpmyadmin
#  clusterIP: None