apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  labels:
    app: zookeeper
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/zookeeper"
