apiVersion: batch/v1
kind: Job
metadata:
  name: job-create-topics
  namespace: kafka
  labels:
    app: kafka
spec:
  template:
    metadata:
      labels:
        app: kafka
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: app-kafka-init-create-topics
          image: busybox
          command:
            - /bin/sh
            - -c
            - 'until [ "imok" = "$(echo ruok | nc -w 1 app-kafka.kafka.svc.cluster.local 29092)" ] ; do echo waiting for kafka ; sleep 1 ; done'
          env:
            - name: SERVICE_TYPE
              value: "init"
      containers:
        - image: confluentinc/cp-kafka:5.0.0
          name: kafka-create-topics
          command:
            - /bin/sh
            - -c
            - 'kafka-topics --create --topic quickstart-avro-offsets --partitions 1 --replication-factor 1 --if-not-exists --zookeeper app-zookeeper.zookeeper.svc.cluster.local:32181'
